// TEMPLATE — copy as environment.ts and environment.prod.ts
// Actual files are auto-generated by: node scripts/generate-env.mjs
// They read from .NET User Secrets + optional .env file. See scripts/generate-env.mjs.
export const environment = {
  production: false,
  apiBaseUrl: 'https://localhost:7040/api/v1',
  auth0: {
    domain: '<YOUR_AUTH0_DOMAIN>',
    clientId: '<YOUR_AUTH0_CLIENT_ID>',
    redirectUri: 'http://localhost:4200/auth/callback',
    audience: 'api://mediahandler',
  },
};
