// Generates src/environments/environment.ts and environment.prod.ts from .NET User Secrets (primary)
// with an optional .env file for overrides.
//
// .NET User Secrets location (Windows):
//   %APPDATA%\Microsoft\UserSecrets\{UserSecretsId}\secrets.json
//
// The UserSecretsId comes from MediaHandler.API\MediaHandler.API\MediaHandler.API.csproj.
// Run automatically via the prestart / prebuild npm hooks.

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import os from 'os';

const USER_SECRETS_ID = '74395325-16b4-4b59-8a0c-78c9b9afddc1';
const ENV_FILE = '.env';
const OUT_DEV  = 'src/environments/environment.ts';
const OUT_PROD = 'src/environments/environment.prod.ts';

// --- 1. Load .NET User Secrets ---
const secretsPath =
  os.platform() === 'win32'
    ? join(process.env['APPDATA'] ?? '', 'Microsoft', 'UserSecrets', USER_SECRETS_ID, 'secrets.json')
    : join(os.homedir(), '.microsoft', 'usersecrets', USER_SECRETS_ID, 'secrets.json');

let dotnetSecrets = {};
if (existsSync(secretsPath)) {
  dotnetSecrets = JSON.parse(readFileSync(secretsPath, 'utf-8').replace(/^\uFEFF/, ''));
  console.log(`[generate-env] Loaded .NET User Secrets from ${secretsPath}`);
} else {
  console.warn(`[generate-env] .NET User Secrets not found at ${secretsPath}`);
}

// --- 2. Load optional .env overrides ---
let dotEnv = {};
if (existsSync(ENV_FILE)) {
  for (const line of readFileSync(ENV_FILE, 'utf-8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    const key = trimmed.slice(0, idx).trim();
    const value = trimmed.slice(idx + 1).trim().replace(/^["']|["']$/g, '');
    dotEnv[key] = value;
  }
  console.log(`[generate-env] Loaded .env overrides from ${ENV_FILE}`);
}

// --- 3. Resolve values (.env overrides .NET secrets) ---
const resolve = (dotNetKey, envKey, fallback) =>
  dotEnv[envKey] ?? dotnetSecrets[dotNetKey] ?? fallback;

const apiBaseUrl     = resolve('',              'API_BASE_URL',        'https://localhost:7001/api/v1');
// Okta:Domain is stored as 'https://domain' — strip protocol for Auth0
const rawDomain      = resolve('Okta:Domain',   'AUTH0_DOMAIN',        '');
const auth0Domain    = rawDomain.replace(/^https?:\/\//, '');
const auth0ClientId  = resolve('Okta:ClientId', 'AUTH0_CLIENT_ID',     '');
const redirectUri    = resolve('',              'AUTH0_REDIRECT_URI',  'http://localhost:4200/auth/callback');
const auth0Audience  = resolve('',              'AUTH0_AUDIENCE',      apiBaseUrl);

// Prod-specific overrides
const prodApiBaseUrl  = resolve('', 'PROD_API_BASE_URL',      apiBaseUrl);
const prodRedirectUri = resolve('', 'PROD_AUTH0_REDIRECT_URI', redirectUri);
const prodAudience    = resolve('', 'PROD_AUTH0_AUDIENCE',     auth0Audience);

// --- 4. Validate ---
const missing = [!auth0Domain && 'Okta:Domain', !auth0ClientId && 'Okta:ClientId'].filter(Boolean);
if (missing.length) {
  console.error(`[generate-env] Missing required secrets: ${missing.join(', ')}`);
  console.error(`[generate-env] Add them to .NET User Secrets or .env`);
  process.exit(1);
}

const banner = `// This file is AUTO-GENERATED by scripts/generate-env.mjs
// Source: .NET User Secrets (${USER_SECRETS_ID}) + optional .env overrides
// Do not edit manually — it is gitignored and regenerated on every build.`;

// --- 5. Write environment.ts (development) ---
writeFileSync(OUT_DEV, `${banner}
export const environment = {
  production: false,
  apiBaseUrl: '${apiBaseUrl}',
  auth0: {
    domain: '${auth0Domain}',
    clientId: '${auth0ClientId}',
    redirectUri: '${redirectUri}',
    audience: '${auth0Audience}',
  },
};
`, 'utf-8');
console.log(`[generate-env] ${OUT_DEV} written`);

// --- 6. Write environment.prod.ts (production) ---
writeFileSync(OUT_PROD, `${banner}
export const environment = {
  production: true,
  apiBaseUrl: '${prodApiBaseUrl}',
  auth0: {
    domain: '${auth0Domain}',
    clientId: '${auth0ClientId}',
    redirectUri: '${prodRedirectUri}',
    audience: '${prodAudience}',
  },
};
`, 'utf-8');
console.log(`[generate-env] ${OUT_PROD} written`);
